baseURL = "https://oe7drt.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "OE7DRT"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-131656855-5"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/blog/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "my personal website"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "MMDVM"
    url = "/mmdvm-hotspot/"
    weight = 4
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 5
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 6
