[build]
	publish = "public"
	command = "hugo --gc --minify"

[build.lifecycle]
  onSuccess = "npm run algolia"

[context.production.environment]
	HUGO_VERSION = "0.60.1"
	HUGO_ENV = "production"

[context.deploy-preview]
	command = "hugo --gc --minify -DEF -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
	HUGO_VERSION = "0.60.1"

# I've set up _headers for this
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
#     # use this to clear HSTS settings
#     # Strict-Transport-Security = "max-age=0; includeSubDomains;"
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Referrer-Policy = "no-referrer"
#     X-Content-Type-Options = "nosniff"
